### Dependencies Role: install_docker ###
- name: Install and configure Docker
  hosts: web
  become: true

  tasks:
    - name: Ensure apt keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key as an .asc file
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
        state: present
        
    - name: Update cache and install prerequisites
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose
        - git

