global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: "oyogbeche@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik.yaml"

http:
  routers:
    frontend:
      rule: "Host(`oyogbeche.tech`) && PathPrefix(`/`)"
      entryPoints:
        - websecure
      service: frontend-service
      tls:
        certResolver: myresolver

    auth_api:
      rule: "Host(`oyogbeche.tech`) && PathPrefix(`/auth`)"
      entryPoints:
        - websecure
      service: auth-service
      tls:
        certResolver: myresolver

    todos_api:
      rule: "Host(`oyogbeche.tech`) && PathPrefix(`/todos`)"
      entryPoints:
        - websecure
      service: todos-service
      tls:
        certResolver: myresolver

    users_api:
      rule: "Host(`oyogbeche.tech`) && PathPrefix(`/users`)"
      entryPoints:
        - websecure
      service: users-service
      tls:
        certResolver: myresolver

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:8000"
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-api:8081"
    todos-service:
      loadBalancer:
        servers:
          - url: "http://todos-api:8082"
    users-service:
      loadBalancer:
        servers:
          - url: "http://users-api:8083"
